test:
  adapter: postgresql
  database: redmine
  username: postgres
  password: postgres
  #password: $POSTGRES_DATABASE
  password: $postgres_database
  host: localhost
  encoding: utf8
  template: template0
