version: 2.1

executors:
  setup:
    docker:
      - image: ruby:2.6-slim-stretch
    environment:
        DEBIAN_FRONTEND: noninteractive
        RUBYOPT: -EUTF-8
commands:
  setup_environment:
    description: "setup environment"
    steps:
      - checkout
      - run: mkdir -p /usr/share/man/man1
      - run: mkdir -p /usr/share/man/man7
      - run: apt-get update
      - run: apt-get install -y postgresql postgresql-client postgresql-server-dev-9.6
      - run: psql --version
      - run: apt-get update
      - run: apt-get install -y build-essential zlib1g-dev libssl-dev libreadline-dev libyaml-dev libcurl4-openssl-dev libffi-dev pkg-config
      - run: apt-get install -y apache2 apache2-dev libapr1-dev libaprutil1-dev
      - run: apt-get install -y imagemagick libmagick++-dev
      - run: apt-get install -y cvs mercurial subversion git bzr
      - run: apt-get install -y debconf-utils tzdata wget
      # postgres
      - run: /etc/init.d/postgresql start
      - run: su - postgres -c "psql -U postgres -d postgres -c \"alter user postgres with password 'postgres';\""
      - run: apt-get install -y curl unzip
      - run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - run: echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - run: rm -rf /var/lib/apt/lists/*
      - run: apt-get update
      - run: apt-get install -y --allow-unauthenticated google-chrome-stable
      - run: wget http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
      - run: unzip chromedriver_linux64.zip
      - run: chmod 755 chromedriver
      - run: mv chromedriver /usr/local/bin/
  build_myredmine:
    description: "build MyRedmine"
    steps:
      #- run: cp ./circleci_files/database.yml ./config/database.yml
      #- checkout
      - run:
          working_directory: lib/redmine
          command: |
            git checkout stable-1.1
            cp ../../circleci_files/database_postgres.yml ../../config/database.yml
            cp ../../circleci_files/change_time_zone.sh change_time_zone.sh
            cp ../../circleci_files/skip_test.rb skip_test.rb
            git clone https://github.com/akiko-pusu/redmine_issue_templates ../../plugins/redmine_issue_templates
            cp ../../plugins/redmine_issue_templates/Gemfile.local ../../plugins/redmine_issue_templates/Gemfile
            git clone https://github.com/onozaty/redmine-view-customize ../../plugins/view_customize
            git clone https://github.com/vividtone/redmine_vividtone_my_page_blocks ../../plugins/redmine_vividtone_my_page_blocks
            bundle install
            echo "bundle install"
            bundle exec rake db:create RAILS_ENV=test
            echo "bundle exec rake db:create RAILS_ENV=test"
            bundle exec rails db:environment:set RAILS_ENV=test
            echo "bundle exec rails db:environment:set RAILS_ENV=test"
            bundle exec rake generate_secret_token
            echo "bundle exec rake generate_secret_token"
            #bundle exec rake db:create RAILS_ENV=test
            echo "bundle exec rake db:create:all RAILS_ENV=test"
            bundle exec rake db:migrate RAILS_ENV=test
            echo "bundle exec rake db:migrate RAILS_ENV=test"
            bundle exec rake test:scm:setup:all
            echo "bundle exec rake test:scm:setup:all"
            bundle exec rake test:scm:update
            echo "bundle exec rake test:scm:update"
            bundle exec rake redmine:plugins:migrate NAME=redmine_issue_templates RAILS_ENV=test
            bundle exec rake redmine:plugins:migrate NAME=view_customize RAILS_ENV=test
            bundle exec rake redmine:plugins:migrate NAME=redmine_vividtone_my_page_blocks RAILS_ENV=test
  test_redmine_utc:
    description: "test redmine utc"
    steps:
      - run:
          working_directory: lib/redmine
          command: |
            touch build_result.txt
            sh change_time_zone.sh UTC > build_result.txt
            cat build_result.txt
      - run:
          command: |
            echo "fail test-utc"
            cat build_result.txt
          when: on_fail
  test_redmine_tokyo:
    description: "test redmine tokyo"
    steps:
      - run:
          working_directory: lib/redmine
          command: |
            ruby skip_test.rb TOKYO_SKIP_TESTS
            sh change_time_zone.sh Tokyo > build_result.txt
            cat build_result.txt
      - run:
          command: |
            echo "fail test-tokyo"
            cat build_result.txt
          when: on_fail
  test_redmine_samoa:
    description: "test redmine samoa"
    steps:
      - run:
          working_directory: lib/redmine
          command: |
            ruby skip_test.rb SAMOA_SKIP_TESTS
            sh change_time_zone.sh "American Samoa" > build_result.txt
            cat build_result.txt
      - run:
          command: |
            echo "fail test-american_samoa"
            cat build_result.txt
          when: on_fail
jobs:
  redmine-test:
    executor:
      name: setup
    steps:
      - setup_environment
      - build_myredmine
      - test_redmine_utc
      - test_redmine_tokyo
      - test_redmine_samoa
workflows:
  normal:
    jobs:
      - redmine-test
