version: 2.1

executors:
  setup:
    docker:
      - image: ruby:2.6-slim-stretch
    environment:
        DEBIAN_FRONTEND: noninteractive
        RUBYOPT: -EUTF-8
commands:
  test:    
    steps:
      - run:
         working_directory: lib/redmine
         command: |
           echo "<< parameters.test >>"
jobs:
  redmine-test:
    parameters:
      test:
        description: "test paramaters"
        type: string
        executor:
          name: setup
        steps:
          - test
workflows:
  normal:
    jobs:
      - redmine-test
