version: 2.1

executors:
  setup:
    docker:
      - image: ruby:2.6-slim-stretch
    environment:
        DEBIAN_FRONTEND: noninteractive
        RUBYOPT: -EUTF-8
commands:
  test:
    parameters:
      to:
        type: string
        default: "test"
    steps:
      - run:
         command: |
           echo << parameters.to >>
jobs:
  redmine-test:
    steps:
      - test:
          to: "test paramaters"
          type: string
workflows:
  normal:
    jobs:
      - redmine-test
